#!/usr/bin/env zsh

# dbbolton
# https://github.com/dbb

git_dir="${HOME}/src/githome"
action="$1"
name="$2"

cd $git_dir && git pull

## This function is for "downloading" a file-- i.e. get the latest version 
## from the master branch and copy it to ~.
down () {
    file="${git_dir}/${name}"
    if [[ -e $file ]]; then
        if [[ -n $( diff ~/${input} $file ) ]]; then
            cp -rv $file ~
        else
            print "Files are the same."
        fi
    else
        found $git_dir 4
    fi
}

## This function is for "uploading" a local file-- i.e. copy it from ~ to the 
## proper git dir.
up () {
    file="${HOME}/${name}"
    if [[ -e $file ]]; then
        cp -rv ~/${file} $git_dir
        cd $git_dir
        git add $file
        git commit -m "Update $file"
        git push -u origin master
    else
        found $HOME 1
    fi
}

found() {
    place=$1
    maxdepth=$2
    print "MAX $maxdepth"
    results=( ${(f)"$( find $place -maxdepth $maxdepth -iname "*$name*"  )"} )
    print "Not such file: '$name'.\n"
    if [[ -n $results ]]; then
        print "Did you mean:\n"
        for i in $results; {
            print $i
        }
    fi
}

if [[ $action == 'up' ]]; then
    up $name
elif [[ $action == 'down' ]]; then
    down $name
else
    print "invalid action: $action\n"
    return 1;
fi

