#!/usr/bin/env zsh

# dbbolton
# https://github.com/dbb

## This script is for "uploading" a local file-- i.e. copy it from ~ to the 
## proper git dir.

input="$1"
found=( ${(f)"$( find . -iname "*$1i*" )"} )

if [[ -e $1 ]]; then
    if [[ -n $( diff ~/$1 ./$1 ) ]]; then

        print "copying ~/$1 to ."
        cp ~/$1 .
        git add $1
        git commit -m "Update $1"
    else
        print "Files are the same"
    fi


else

    print "Not such file: '$input'.\n""Did you mean:\n"

    for i in $found; {
        print $i
    }

    exit 1;

fi

